version: '3.5'
services:

  terraform:
    build:
      context: ..
      dockerfile: ./Dockerfile
    platform: linux/amd64
    image: terraform-docker-image:latest
    container_name: terraform-docker-image
    restart: "no"
    

    ### 持續執行
    command: ["tail","-f","/dev/null"]
    
    ### 批次執行
    #command: ["terraform","-version"]


    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

































